// Bahasa Melayu text, keyed by the English text used in the code.
// lang.test.ts checks that every t() call's text has an entry here.

export const ms: Record<string, string> = {
  // Everyday words
  Account: 'Akaun',
  Back: 'Kembali',
  Barber: 'Barber',
  Barbers: 'Barber',
  Bookings: 'Tempahan',
  Cancel: 'Batal',
  Cancelled: 'Dibatalkan',
  Closed: 'Tutup',
  Confirmed: 'Disahkan',
  Copied: 'Disalin',
  Copy: 'Salin',
  Customer: 'Pelanggan',
  Delete: 'Padam',
  Done: 'Selesai',
  Edit: 'Ubah',
  Email: 'E-mel',
  From: 'Dari',
  Go: 'Pergi',
  Hide: 'Sorok',
  Hours: 'Waktu',
  Language: 'Bahasa',
  Me: 'Saya',
  Minutes: 'Minit',
  Name: 'Nama',
  'No-show': 'Tidak hadir',
  Off: 'Cuti',
  Open: 'Buka',
  Password: 'Kata laluan',
  Past: 'Lepas',
  Preview: 'Pratonton',
  Remove: 'Buang',
  Save: 'Simpan',
  'Saved.': 'Disimpan.',
  Search: 'Cari',
  Service: 'Servis',
  Services: 'Servis',
  Share: 'Kongsi',
  Show: 'Papar',
  To: 'Hingga',
  Upcoming: 'Akan datang',
  'Keep it': 'Kekalkan',

  // Days and times
  Sun: 'Ahd',
  Mon: 'Isn',
  Tue: 'Sel',
  Wed: 'Rab',
  Thu: 'Kha',
  Fri: 'Jum',
  Sat: 'Sab',
  Yesterday: 'Semalam',
  Today: 'Hari ini',
  Tomorrow: 'Esok',
  Morning: 'Pagi',
  Afternoon: 'Tengah hari',
  Evening: 'Petang & malam',
  am: 'PG',
  pm: 'PTG',
  '{m} min': '{m} min',
  '{h} hr': '{h} jam',
  '{h} hr {m} min': '{h} jam {m} min',
  'Every day': 'Setiap hari',
  'varied hours': 'waktu berbeza',
  'No hours set, so not bookable': 'Waktu belum ditetapkan, jadi tidak boleh ditempah',

  // Welcome, sign in and sign up
  'Book your next haircut in seconds. No calls, no waiting for DM replies.':
    'Tempah potongan rambut dalam beberapa saat. Tak perlu telefon, tak perlu tunggu balasan DM.',
  'Find a barber': 'Cari barber',
  'Sign in': 'Log masuk',
  'Are you a barber?': 'Anda seorang barber?',
  'Get your own booking link, fill your chairs and cut down on no-shows. Free for your first month.':
    'Dapatkan pautan tempahan sendiri, penuhkan kerusi dan kurangkan pelanggan yang tidak hadir. Percuma untuk bulan pertama.',
  'Set up my shop': 'Sediakan kedai saya',
  'Create account': 'Daftar akaun',
  'Create an account': 'Daftar akaun',
  'New here?': 'Baru di sini?',
  'Forgot password?': 'Lupa kata laluan?',
  'Check your email': 'Semak e-mel anda',
  'We sent a confirmation link to {email}. Tap it, then come back and sign in.':
    'Kami telah hantar pautan pengesahan ke {email}. Tekan pautan itu, kemudian kembali dan log masuk.',
  'Go to sign in': 'Pergi ke log masuk',
  'I am a': 'Saya seorang',
  'Barber / shop owner': 'Barber / pemilik kedai',
  'Your first month is free. You can set up your shop right after this.':
    'Bulan pertama anda percuma. Anda boleh sediakan kedai sejurus selepas ini.',
  'Full name': 'Nama penuh',
  'Phone (WhatsApp)': 'Telefon (WhatsApp)',
  'Customers will see this to contact you.': 'Pelanggan akan nampak nombor ini untuk hubungi anda.',
  'Your barber can reach you here if plans change.': 'Barber anda boleh hubungi anda di sini jika ada perubahan.',
  'At least 8 characters.': 'Sekurang-kurangnya 8 aksara.',

  // Password reset
  'Reset password': 'Tetap semula kata laluan',
  'Enter the email you signed up with and we’ll send you a code to set a new password.':
    'Masukkan e-mel yang anda guna semasa mendaftar dan kami akan hantar kod untuk tetapkan kata laluan baharu.',
  'Send code': 'Hantar kod',
  'If {email} has an account, a code is on its way. It can take a minute; check your spam folder too.':
    'Jika {email} ada akaun, kod sedang dihantar. Mungkin ambil masa seminit; semak juga folder spam.',
  'Code from the email': 'Kod daripada e-mel',
  'New password': 'Kata laluan baharu',
  'Set new password': 'Tetapkan kata laluan baharu',
  'Send a new code': 'Hantar kod baharu',
  'Use a different email': 'Guna e-mel lain',
  'That code is wrong or has expired. Check the latest email, or send a new code.':
    'Kod itu salah atau sudah tamat tempoh. Semak e-mel terkini, atau hantar kod baharu.',

  // Account
  'You’re browsing as a guest.': 'Anda sedang melayari sebagai tetamu.',
  'Sign out': 'Log keluar',
  'Delete account': 'Padam akaun',
  'Delete your account?': 'Padam akaun anda?',
  'This deletes your shop, booking link, services and all its bookings. Let customers with upcoming bookings know first. This can’t be undone.':
    'Ini akan memadam kedai, pautan tempahan, servis dan semua tempahan anda. Maklumkan dahulu kepada pelanggan yang ada tempahan akan datang. Tindakan ini tidak boleh dibatalkan.',
  'Your upcoming bookings will be cancelled. This can’t be undone.':
    'Tempahan anda yang akan datang akan dibatalkan. Tindakan ini tidak boleh dibatalkan.',

  // Finding a barber
  'Shop name or area, e.g. Sungai Chua': 'Nama kedai atau kawasan, cth. Sungai Chua',
  'Couldn’t load barbers': 'Tidak dapat memuatkan barber',
  'Check your connection and try again.': 'Semak sambungan internet anda dan cuba lagi.',
  'Try again': 'Cuba lagi',
  'Loading barbers…': 'Memuatkan barber…',
  'No matches': 'Tiada padanan',
  'Try another name or area.': 'Cuba nama atau kawasan lain.',
  'No barbers yet': 'Belum ada barber',
  'Barbers in your area are joining soon. Check back shortly.':
    'Barber di kawasan anda akan menyertai tidak lama lagi. Sila semak semula nanti.',
  'From {price}': 'Dari {price}',
  '1 barber': '1 barber',
  '{count} barbers': '{count} barber',

  // Booking at a shop
  'Shop not found': 'Kedai tidak dijumpai',
  'This booking link may be wrong, or the shop isn’t taking bookings right now.':
    'Pautan tempahan ini mungkin salah, atau kedai tidak menerima tempahan buat masa ini.',
  'Find another barber': 'Cari barber lain',
  'Not taking online bookings yet': 'Belum menerima tempahan dalam talian',
  'Message the shop to book for now.': 'Hubungi kedai untuk menempah buat masa ini.',
  '1. Pick a service': '1. Pilih servis',
  '2. Pick a barber': '2. Pilih barber',
  '2. Pick a time': '2. Pilih masa',
  '3. Pick a time': '3. Pilih masa',
  'Any barber': 'Mana-mana barber',
  'Checking free times…': 'Menyemak masa kosong…',
  'No free times this day. Try another day.': 'Tiada masa kosong pada hari itu. Cuba hari lain.',
  'No free times this day. Try another day or any barber.':
    'Tiada masa kosong pada hari itu. Cuba hari lain atau mana-mana barber.',
  'Pay at the shop.': 'Bayar di kedai.',
  'Note for your barber (optional)': 'Nota untuk barber anda (pilihan)',
  'e.g. low fade, keep the top long': 'cth. low fade, rambut atas kekal panjang',
  'Confirm booking': 'Sahkan tempahan',
  'Sign in to book': 'Log masuk untuk tempah',
  'Opening hours': 'Waktu operasi',
  'You’re booked!': 'Tempahan berjaya!',
  '{service} with {barber}': '{service} bersama {barber}',
  '{service} on {day} at {time}': '{service} pada {day} jam {time}',
  '{service} on {day} at {time}.': '{service} pada {day} jam {time}.',
  'Can’t make it? Cancel from My bookings so someone else can take the slot.':
    'Tak dapat datang? Batalkan di Tempahan saya supaya orang lain boleh ambil slot itu.',
  'WhatsApp the shop': 'WhatsApp kedai',
  'See my bookings': 'Lihat tempahan saya',

  // A customer's bookings
  'My bookings': 'Tempahan saya',
  'Your bookings live here': 'Tempahan anda ada di sini',
  'Sign in to see and manage your appointments.': 'Log masuk untuk lihat dan urus temujanji anda.',
  'No bookings yet': 'Belum ada tempahan',
  'Find a barber and grab a slot.': 'Cari barber dan tempah slot.',
  'Cancel booking?': 'Batalkan tempahan?',
  'Cancel booking': 'Batalkan tempahan',
  'your barber': 'barber anda',
  'WhatsApp shop': 'WhatsApp kedai',
  '{service} at {shop}': '{service} di {shop}',
  'Book again': 'Tempah lagi',

  // Barber: bookings for the day
  'Get ready for bookings': 'Bersedia untuk menerima tempahan',
  'Add your services and prices': 'Tambah servis dan harga anda',
  'Check your barbers and working hours': 'Semak barber dan waktu kerja anda',
  'Go live and share your booking link': 'Buka tempahan dan kongsi pautan tempahan anda',
  '+ Add booking or block time': '+ Tambah tempahan atau sekat masa',
  'No bookings': 'Tiada tempahan',
  'Share your booking link to fill this day.': 'Kongsi pautan tempahan anda untuk penuhkan hari ini.',
  'Whole day': 'Sepanjang hari',
  Blocked: 'Disekat',
  '{name} (added by you)': '{name} (ditambah oleh anda)',
  'Remove this block?': 'Buang sekatan ini?',
  'Customers will be able to book this time again.': 'Pelanggan boleh menempah masa ini semula.',
  'Cancel this booking?': 'Batalkan tempahan ini?',
  '{who} · {service} at {time}. Let them know on WhatsApp.':
    '{who} · {service} jam {time}. Maklumkan kepada mereka melalui WhatsApp.',
  'Hi {who}, this is {shop} about your {service} on {day} at {time}.':
    'Hai {who}, ini {shop} berkenaan {service} anda pada {day} jam {time}.',

  // Barber: adding a booking or blocking time
  'Add to the day': 'Tambah ke jadual',
  'Customer booking': 'Tempahan pelanggan',
  'Block time': 'Sekat masa',
  'For walk-ins and bookings that came by WhatsApp or phone. Online customers can no longer take this time.':
    'Untuk pelanggan walk-in dan tempahan melalui WhatsApp atau telefon. Pelanggan dalam talian tidak boleh ambil masa ini lagi.',
  'For breaks, errands or a day off. Online customers can’t book this time.':
    'Untuk rehat, urusan peribadi atau cuti. Pelanggan dalam talian tidak boleh menempah masa ini.',
  'How long': 'Berapa lama',
  'Start time': 'Masa mula',
  '24-hour time.': 'Format 24 jam.',
  'Customer name': 'Nama pelanggan',
  'e.g. Pak Abu': 'cth. Pak Abu',
  'Customer phone (optional)': 'Telefon pelanggan (pilihan)',
  'Note (optional)': 'Nota (pilihan)',
  'e.g. booked on WhatsApp': 'cth. tempah melalui WhatsApp',
  'Reason (optional)': 'Sebab (pilihan)',
  'e.g. Hari Raya, day off': 'cth. Hari Raya, cuti',
  'e.g. lunch, errand': 'cth. makan tengah hari, urusan',
  'Add booking': 'Tambah tempahan',
  'Block the day': 'Sekat hari ini',
  'Pick a barber.': 'Pilih barber.',
  'Pick a service.': 'Pilih servis.',
  'Enter the start time, e.g. 14:30.': 'Masukkan masa mula, cth. 14:30.',
  'Add the customer’s name.': 'Masukkan nama pelanggan.',
  'There are bookings on this day. Cancel them first (and let the customers know), then block the day.':
    'Ada tempahan pada hari ini. Batalkan dahulu (dan maklumkan kepada pelanggan), kemudian sekat hari ini.',

  // Barber: services
  'Your menu': 'Menu anda',
  'No services yet': 'Belum ada servis',
  'Add what you offer so customers can book it.': 'Tambah servis yang anda tawarkan supaya pelanggan boleh menempah.',
  'hidden from customers': 'disorok daripada pelanggan',
  'Quick add': 'Tambah pantas',
  'You can change the price and time after adding.': 'Anda boleh ubah harga dan masa selepas menambah.',
  'Add a service': 'Tambah servis',
  'Edit {name}': 'Ubah {name}',
  'Delete {name}?': 'Padam {name}?',
  'Customers will no longer see it. Past bookings keep their details. To bring it back later, use Hide instead.':
    'Pelanggan tidak akan nampak lagi. Tempahan lepas kekal butirannya. Untuk guna semula nanti, pilih Sorok.',
  'e.g. Skin fade + beard': 'cth. Skin fade + janggut',
  'Price (RM)': 'Harga (RM)',
  'Save service': 'Simpan servis',
  'Add service': 'Tambah servis',
  'Give the service a name.': 'Berikan nama untuk servis ini.',
  'Time should be between 5 and 480 minutes.': 'Masa mestilah antara 5 hingga 480 minit.',
  'Enter a price in RM.': 'Masukkan harga dalam RM.',
  Haircut: 'Potong rambut',
  Fade: 'Fade',
  'Beard trim': 'Trim janggut',
  'Kids cut': 'Potong rambut kanak-kanak',

  // Barber: team and hours
  'One per chair. Customers can pick a barber or take whoever is free.':
    'Seorang bagi setiap kerusi. Pelanggan boleh pilih barber atau sesiapa yang lapang.',
  'Your team': 'Pasukan anda',
  'Add yourself and anyone who cuts in your shop.': 'Tambah diri anda dan sesiapa yang menggunting di kedai anda.',
  'Away, not taking bookings': 'Bercuti, tidak menerima tempahan',
  'Mark away': 'Tanda bercuti',
  'Back at work': 'Kembali bekerja',
  'Add a barber': 'Tambah barber',
  'Add barber': 'Tambah barber',
  'e.g. Danial': 'cth. Danial',
  'New barbers start with 10am–8pm, Monday to Saturday. Tap Hours to change.':
    'Barber baharu bermula 10 pagi–8 malam, Isnin hingga Sabtu. Tekan Waktu untuk ubah.',
  'Working hours': 'Waktu kerja',
  'Barber name': 'Nama barber',
  'Copy Monday’s hours to all open days': 'Salin waktu Isnin ke semua hari buka',
  'Break from': 'Rehat dari',
  'Break to': 'Rehat hingga',
  'Remove break': 'Buang rehat',
  '+ Add break (e.g. Friday prayers)': '+ Tambah rehat (cth. solat Jumaat)',
  '+ Add break': '+ Tambah rehat',
  'Use 24-hour time, e.g. 21:30 for 9:30pm.': 'Guna format 24 jam, cth. 21:30 untuk 9:30 malam.',
  'Save hours': 'Simpan waktu',
  'use times like 09:00 or 21:30.': 'guna masa seperti 09:00 atau 21:30.',
  'closing time must be after opening time.': 'waktu tutup mesti selepas waktu buka.',
  'use times like 13:00 for the break.': 'guna masa seperti 13:00 untuk rehat.',
  'the break must sit inside opening hours.': 'waktu rehat mesti dalam waktu kerja.',

  // Barber: shop
  'My shop': 'Kedai saya',
  'Set up your shop': 'Sediakan kedai anda',
  'This is what customers see. You can change any of it later.':
    'Inilah yang pelanggan nampak. Anda boleh ubah bila-bila masa.',
  'Subscription active': 'Langganan aktif',
  'Free trial: 1 day left': 'Percubaan percuma: tinggal 1 hari',
  'Free trial: {count} days left': 'Percubaan percuma: tinggal {count} hari',
  'Trial ended, customers can no longer book': 'Percubaan tamat, pelanggan tidak boleh menempah',
  'You are live': 'Tempahan dibuka',
  'Not live yet': 'Belum dibuka',
  'Customers can find you and book. Share your link everywhere.':
    'Pelanggan boleh cari dan tempah anda. Kongsi pautan anda di mana-mana.',
  'Go live when your services and hours are ready.': 'Buka tempahan apabila servis dan waktu kerja anda sudah sedia.',
  'Your free month ends on {day}.': 'Bulan percuma anda tamat pada {day}.',
  'Pause bookings': 'Tutup tempahan sementara',
  'Go live': 'Buka tempahan',
  'Your booking link': 'Pautan tempahan anda',
  'Put it in your Instagram bio, WhatsApp status and on a poster at the shop.':
    'Letak di bio Instagram, status WhatsApp dan poster di kedai.',
  'Book your next cut at {shop}: {link}': 'Tempah potongan rambut seterusnya di {shop}: {link}',
  'Shop details': 'Butiran kedai',
  'Shop name': 'Nama kedai',
  'e.g. Kemas Barber Kajang': 'cth. Kemas Barber Kajang',
  'Booking link': 'Pautan tempahan',
  'Letters, numbers and dashes.': 'Huruf, nombor dan sengkang.',
  About: 'Tentang kedai',
  'Fades, beard trims, kids cuts…': 'Fade, trim janggut, potongan kanak-kanak…',
  Address: 'Alamat',
  Area: 'Kawasan',
  'Shop phone (WhatsApp)': 'Telefon kedai (WhatsApp)',
  '@yourshop': '@kedaianda',
  'Save changes': 'Simpan perubahan',
  'Create my shop': 'Cipta kedai saya',

  // Errors from the app, the database and sign-in
  'That name or link is already taken.': 'Nama atau pautan itu sudah digunakan.',
  'Something there is too long or not allowed. Please check and try again.':
    'Ada maklumat yang terlalu panjang atau tidak dibenarkan. Sila semak dan cuba lagi.',
  'Something went wrong. Please try again.': 'Ada masalah. Sila cuba lagi.',
  'You already have {count} upcoming bookings here. Cancel one to book another.':
    'Anda sudah ada {count} tempahan akan datang di sini. Batalkan satu untuk menempah lagi.',
  "Add the customer's name.": 'Masukkan nama pelanggan.',
  'Barber not found.': 'Barber tidak dijumpai.',
  'Booking not found.': 'Tempahan tidak dijumpai.',
  'Closing time must be after opening time.': 'Waktu tutup mesti selepas waktu buka.',
  'Not signed in.': 'Anda belum log masuk.',
  'Pick a service, or a length between 5 minutes and 12 hours (a whole day for blocks).':
    'Pilih servis, atau tempoh antara 5 minit hingga 12 jam (sepanjang hari untuk sekatan).',
  'Please keep your note under 280 characters.': 'Sila pastikan nota kurang daripada 280 aksara.',
  'Please sign in to book.': 'Sila log masuk untuk menempah.',
  'Service not found.': 'Servis tidak dijumpai.',
  'Some of those hours overlap on the same day.': 'Ada waktu yang bertindih pada hari yang sama.',
  'Sorry, that time was just taken. Please pick another.': 'Maaf, masa itu baru sahaja diambil. Sila pilih masa lain.',
  'That barber already has a booking at that time.': 'Barber itu sudah ada tempahan pada masa itu.',
  'That time has been booked by someone else since.': 'Masa itu sudah ditempah oleh orang lain.',
  'This service is no longer available.': 'Servis ini tidak lagi ditawarkan.',
  'You can mark this once the appointment has started.': 'Anda boleh tanda ini selepas temujanji bermula.',
  'You can only cancel an upcoming booking.': 'Anda hanya boleh membatalkan tempahan yang akan datang.',
  'Invalid login credentials': 'E-mel atau kata laluan salah.',
  'User already registered': 'E-mel ini sudah didaftarkan. Cuba log masuk.',
  'Email not confirmed': 'E-mel belum disahkan. Semak e-mel anda untuk pautan pengesahan.',
  'New password should be different from the old password.': 'Kata laluan baharu mesti berbeza daripada yang lama.',
  'Unable to validate email address: invalid format': 'Alamat e-mel itu tidak sah.',

  // Demo build (scripts/build-demo.mjs)
  Demo: 'Demo',
  'Try it with sample shops in Kajang': 'Cuba dengan kedai contoh di Kajang',
  'As a customer you are Hakim. As a barber you are Ali, who runs Ali Barber Sungai Chua.':
    'Sebagai pelanggan, anda ialah Hakim. Sebagai barber, anda ialah Ali, pemilik Ali Barber Sungai Chua.',
  'Try as a customer': 'Cuba sebagai pelanggan',
  'Try as a barber': 'Cuba sebagai barber',
  'Nothing here is real and nothing is sent anywhere. Your changes stay on this device.':
    'Semua di sini hanya contoh dan tiada apa-apa dihantar. Perubahan anda kekal di peranti ini.',
  'Start the demo again': 'Mulakan semula demo',
  'Start the demo again?': 'Mulakan semula demo?',
  'Every booking, shop and account goes back to the sample data.':
    'Semua tempahan, kedai dan akaun akan kembali kepada data contoh.',
  'Start again': 'Mula semula',
  'See the barber side': 'Lihat sebagai barber',
  'See the customer side': 'Lihat sebagai pelanggan',
  'Demo accounts: {customer} (customer) or {barber} (barber). Password: {password}':
    'Akaun demo: {customer} (pelanggan) atau {barber} (barber). Kata laluan: {password}',
  'This is the demo, so no email is sent. Use code {code}.': 'Ini demo, jadi tiada e-mel dihantar. Gunakan kod {code}.',
};
